spring.application.name=configuration-service

server.port=${PORT:8888}

spring.profiles.active=${ENV:local}

spring.cloud.config.server.git.uri=${GIT_URI:https://github.com/DrTrng/config-repo}
spring.cloud.config.server.git.default-label=${GIT_BRANCH:main}
spring.cloud.config.server.git.clone-on-start=true
management.endpoints.web.exposure.include=health,info