name: Auth Service CI/CD

on:
  push:
    paths:
      - "auth/**"
      - "core/**"
  pull_request:
    paths:
      - "auth/**"
      - "core/**"

jobs:
  build-auth:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Auth Service
        run: |
          cd services/auth
          docker build -t auth-service .

      # - name: Push Image
      #   run: |
      #     docker tag auth-service myrepo/auth-service:${{ github.sha }}
      #     docker push myrepo/auth-service:${{ github.sha }}