name: Build Product Service

on:
  push:
    paths:
      - "auth-service/**"
      - "core-service/**"

jobs:
  build-product:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build auth service
        run: |
          cd auth-service
          mvn clean package -DskipTests