name: Build Auth Service

on:
  push:
    branches:
      - "**"
    paths:
      - "auth-service/**"
      - "core-service/**"

jobs:
  build-product:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build auth service
        run: |
          cd auth-service
          mvn clean package -DskipTests