name: Build Payment Service

on:
  push:
    branches:
      - "main"
    paths:
      - "payment-service/**"

jobs:
  build-payment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build payment service
        run: mvn clean install -pl payment-service -am -DskipTests