name: Build Product Service

on:
  push:
    paths:
      - "product-service/**"
      - "core-service/**"

jobs:
  build-product:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 👇 STEP DEBUG (RẤT QUAN TRỌNG)
      - name: Debug repo structure
        run: |
          pwd
          ls -la

      - name: Build product service
        run: |
          cd product-service
          mvn clean package -DskipTests