name: Build Product Service

on:
  push:
    paths:
      - "product-service/**"
      - "core-service/**"

jobs:
  build-product:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd product-service
          mvn clean package -DskipTests