name: Build Auth Service

on:
  push:
    paths:
      - "product/**"
      - "core/**"

jobs:
  build-auth:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build auth service
        run: |
          cd product-service
          mvn clean package -DskipTests